language: c

sudo: false

dist: trusty

before_install:
  - cd ..
  - mkdir cortoproject
  - mv examples cortoproject/examples
  - cd cortoproject
  - git clone https://github.com/cortoproject/corto.git
  - git clone https://github.com/cortoproject/c-binding.git
  - git clone https://github.com/cortoproject/json.git
  - git clone https://github.com/cortoproject/xml.git
  - git clone https://github.com/cortoproject/corto-language.git
  - git clone https://github.com/cortoproject/test.git
  - git clone https://github.com/cortoproject/web.git
  - git clone https://github.com/cortoproject/admin.git
  - |+
    echo 'COMPONENTS = %w(corto c-binding json xml corto-language test web admin examples)
    require "#{ENV["CORTO_BUILD"]}/forward"' > rakefile

script:
  - source corto/configure
  - rake

